/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.managment.system;

import java.awt.CardLayout;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author youss
 */
public class mainPanel extends javax.swing.JPanel {
    String userName;
    /**
     * Creates new form mainPanel
     */
    CardLayout cardLayout;
    public mainPanel(String userName) {
        this.userName = userName;
        initComponents();
        cardLayout= (CardLayout)(CardPanels.getLayout());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        TransBut = new javax.swing.JButton();
        DepBut = new javax.swing.JButton();
        DrawBut = new javax.swing.JButton();
        CreditBut = new javax.swing.JButton();
        LogOBut = new javax.swing.JButton();
        DataBut = new javax.swing.JButton();
        CardPanels = new javax.swing.JPanel();
        CardP1 = new javax.swing.JPanel();
        dataUsetPanel1 = new bank.managment.system.DataUserPanel(userName);
        CardP2 = new javax.swing.JPanel();
        depositPanel1 = new bank.managment.system.DepositPanel(userName);
        CardP3 = new javax.swing.JPanel();
        withDrawPanel11 = new bank.managment.system.WithDrawPanel1(userName);
        CardP4 = new javax.swing.JPanel();
        creditPanel1 = new bank.managment.system.CreditPanel(userName);
        CardP5 = new javax.swing.JPanel();
        transferPanel1 = new bank.managment.system.TransferPanel(userName);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(57, 62, 70));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/managment/system/Login Page logo.png")));
        TransBut.setBackground(new java.awt.Color(57, 62, 70));
        TransBut.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TransBut.setForeground(new java.awt.Color(255, 255, 255));
        TransBut.setText("Money Transfer");
        TransBut.setBorder(null);
        TransBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransButActionPerformed(evt);
            }
        });

        DepBut.setBackground(new java.awt.Color(57, 62, 70));
        DepBut.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        DepBut.setForeground(new java.awt.Color(255, 255, 255));
        DepBut.setText("Deposite");
        DepBut.setBorder(null);
        DepBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepButActionPerformed(evt);
            }
        });

        DrawBut.setBackground(new java.awt.Color(57, 62, 70));
        DrawBut.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        DrawBut.setForeground(new java.awt.Color(255, 255, 255));
        DrawBut.setText("WithDraw");
        DrawBut.setBorder(null);
        DrawBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawButActionPerformed(evt);
            }
        });

        CreditBut.setBackground(new java.awt.Color(57, 62, 70));
        CreditBut.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        CreditBut.setForeground(new java.awt.Color(255, 255, 255));
        CreditBut.setText("Credit");
        CreditBut.setBorder(null);
        CreditBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditButActionPerformed(evt);
            }
        });

        LogOBut.setBackground(new java.awt.Color(57, 62, 70));
        LogOBut.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LogOBut.setForeground(new java.awt.Color(255, 255, 255));
        LogOBut.setText("Log Out");
        LogOBut.setBorder(null);
        LogOBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOButActionPerformed(evt);
            }
        });

        DataBut.setBackground(new java.awt.Color(57, 62, 70));
        DataBut.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        DataBut.setForeground(new java.awt.Color(255, 255, 255));
        DataBut.setText("User Data");
        DataBut.setBorder(null);
        DataBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataButActionPerformed(evt);
            }
        });



        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel3Layout.createSequentialGroup()
             .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(0, 35, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(TransBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(CreditBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DrawBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogOBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                 .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)   
                .addContainerGap()
                
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(DataBut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(DepBut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(DrawBut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TransBut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CreditBut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(LogOBut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.LINE_START);

        CardPanels.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout CardP1Layout = new javax.swing.GroupLayout(CardP1);
        CardP1.setLayout(CardP1Layout);
        CardP1Layout.setHorizontalGroup(
            CardP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardP1Layout.createSequentialGroup()
                .addComponent(dataUsetPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CardP1Layout.setVerticalGroup(
            CardP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataUsetPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        CardPanels.add(CardP1, "card1");

        CardP2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CardP2Layout = new javax.swing.GroupLayout(CardP2);
        CardP2.setLayout(CardP2Layout);
        CardP2Layout.setHorizontalGroup(
            CardP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardP2Layout.createSequentialGroup()
                .addComponent(depositPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CardP2Layout.setVerticalGroup(
            CardP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depositPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        CardPanels.add(CardP2, "card2");

        CardP3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CardP3Layout = new javax.swing.GroupLayout(CardP3);
        CardP3.setLayout(CardP3Layout);
        CardP3Layout.setHorizontalGroup(
            CardP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardP3Layout.createSequentialGroup()
                .addComponent(withDrawPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CardP3Layout.setVerticalGroup(
            CardP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(withDrawPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        CardPanels.add(CardP3, "card3");

        CardP4.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout CardP4Layout = new javax.swing.GroupLayout(CardP4);
        CardP4.setLayout(CardP4Layout);
        CardP4Layout.setHorizontalGroup(
            CardP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        CardP4Layout.setVerticalGroup(
            CardP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        CardPanels.add(CardP4, "card4");

        CardP5.setBackground(new java.awt.Color(51, 51, 0));

        javax.swing.GroupLayout CardP5Layout = new javax.swing.GroupLayout(CardP5);
        CardP5.setLayout(CardP5Layout);
        CardP5Layout.setHorizontalGroup(
            CardP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardP5Layout.createSequentialGroup()
                .addComponent(transferPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CardP5Layout.setVerticalGroup(
            CardP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        CardPanels.add(CardP5, "card5");

        add(CardPanels, java.awt.BorderLayout.CENTER);
    }

    private void DataButActionPerformed(java.awt.event.ActionEvent evt) {
        cardLayout.show(CardPanels, "card1");
        dataUsetPanel1.update();
    }

    private void DepButActionPerformed(java.awt.event.ActionEvent evt) {
        cardLayout.show(CardPanels, "card2");  
        depositPanel1.update();
    }

    private void DrawButActionPerformed(java.awt.event.ActionEvent evt) {
        cardLayout.show(CardPanels, "card3");
        withDrawPanel11.update();     // TODO add your handling code here:
    }

    private void CreditButActionPerformed(java.awt.event.ActionEvent evt) {
        cardLayout.show(CardPanels, "card4");
        creditPanel1.update();
        
    }

    private void TransButActionPerformed(java.awt.event.ActionEvent evt) {
        cardLayout.show(CardPanels, "card5"); 
        transferPanel1.update();
    }

    private void LogOButActionPerformed(java.awt.event.ActionEvent evt) {
        GUI.loginPanal.setVisible(true);
        GUI.mainPanalFram.setVisible(false);
        GUI.mainPanalFram.remove(this);
        GUI.log.RemoveData();
        GUI.panel3.RemoveData();
        



    }



    public static javax.swing.JPanel CardP1;
    public javax.swing.JPanel CardP2;
    private javax.swing.JPanel CardP3;
    private javax.swing.JPanel CardP4;
    private javax.swing.JPanel CardP5;
    private javax.swing.JPanel CardPanels;
    private javax.swing.JButton CreditBut;
    private javax.swing.JButton DataBut;
    private javax.swing.JButton DepBut;
    private javax.swing.JButton DrawBut;
    private javax.swing.JButton LogOBut;
    private javax.swing.JButton TransBut;
    private bank.managment.system.CreditPanel creditPanel1;
    private bank.managment.system.DataUserPanel dataUsetPanel1;
    private bank.managment.system.DepositPanel depositPanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private bank.managment.system.TransferPanel transferPanel1;
    private bank.managment.system.WithDrawPanel1 withDrawPanel11;
    private javax.swing.JLabel jLabel1;
}
